# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: AIzaSyDV2gMeeSKqmcqb2M3jRoo3TYL_ZGcCsWk
      REACT_APP_AUTH_DOMAIN: letmeask-f1d93.firebaseapp.com
      REACT_APP_DATABASE_URL: https://letmeask-f1d93-default-rtdb.firebaseio.com
      REACT_APP_PROJECT_ID: letmeask-f1d93
      REACT_APP_STOREGE_BUCKET: letmeask-f1d93.appspot.com
      REACT_APP_MESSAGING_SENDER_ID: 462313366096
      REACT_APP_APP_ID: 1:462313366096:web:f3b91464a32920f86b2755

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
